repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py313]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        language_version: python3

  - repo: https://github.com/charliermarsh/pyright-python
    rev: v1.1.377
    hooks:
      - id: pyright
        args: [--project=pyrightconfig.json]
        language_version: python3

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--fix]
        files: \.md$

  - repo: local
    hooks:
      - id: python-import-sort
        name: Sort Python imports
        entry: python -m isort
        language: system
        types: [python]
        args: [--profile=black]

      - id: trailing-whitespace
        name: Trim trailing whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
