name: CI
on:
  push: { branches: [ master, main ] }
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          mkdir -p reports
          pytest tests --maxfail=1 --disable-warnings \
            --junitxml=reports/junit.xml --cov=. --cov-report=xml:reports/coverage.xml
      
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
          retention-days: 7
      
      - name: Show test summary
        run: |
          echo "📊 Relatórios de teste gerados:"
          ls -la reports/ || echo "Nenhum relatório encontrado"
