name: UI Reporter
on: [push, pull_request]

jobs:
  ui-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run UI Reporter
        run: |
          python -m app.dashboard --report --json --junit --strict --exit-after-report > ui_summary.json
          
      - name: Verify snapshot baseline
        run: |
          python diagnostics/verify_snapshot.py
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-reporter-artifacts
          path: |
            ui_snapshot.txt
            ui_summary.json
            ui_reporter.junit.xml
          retention-days: 30
          
      - name: Resumo no PR
        if: always()
        run: |
          echo "## UI Reporter" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Checks: " >> $GITHUB_STEP_SUMMARY
          python -c "import json, pathlib; p=pathlib.Path('ui_summary.json'); s=json.loads(p.read_text()) if p.exists() else {'checks': {}}; ok=s.get('checks', {}); total=len(ok); passed=sum(1 for v in ok.values() if v); print(f'- {passed}/{total} checks passaram'); [print(f'- {\"✅\" if v else \"❌\"} {k}') for k,v in ok.items()]"
          
      - name: Show summary
        if: always()
        run: |
          echo "=== UI Reporter Summary ==="
          if [ -f ui_summary.json ]; then
            echo "✅ UI Reporter executado com sucesso"
            echo "📊 Checks realizados:"
            python -c "import json; data=json.load(open('ui_summary.json')); [print(f'  {k}: {\"✅\" if v else \"❌\"}') for k,v in data['checks'].items()]"
          else
            echo "❌ UI Reporter falhou"
            exit 1
          fi
