name: UI Reporter
on: [push, pull_request]

jobs:
  ui-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.11', '3.12']
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run UI Reporter
        run: |
          set -e
          export GG_REPORT=1 GG_STRICT=1 GG_JUNIT=1 GG_SEED=1337 GG_FREEZE_TIME=2025-01-01T00:00:00Z
          python -m app.dashboard --report --json --junit --strict --exit-after-report | tee ui_summary.json
          python diagnostics/verify_snapshot.py
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-reporter-${{ matrix.os }}-py${{ matrix.python }}
          path: |
            ui_snapshot.txt
            ui_snapshot.diff
            ui_summary.json
            ui_reporter.junit.xml
          retention-days: 30
          
      - name: Resumo no PR
        if: always()
        run: |
          echo "## UI Reporter (${{ matrix.os }} / py${{ matrix.python }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          python -c "import json, pathlib; p=pathlib.Path('ui_summary.json'); s=json.loads(p.read_text()) if p.exists() else {'checks': {}}; chk=s.get('checks', {}); total=len(chk); passed=sum(map(int, chk.values())); print(f'- {passed}/{total} checks passaram'); [print(f'- {\"✅\" if v else \"❌\"} {k}') for k,v in chk.items()]"
          
      - name: Show summary
        if: always()
        run: |
          echo "=== UI Reporter Summary (${{ matrix.os }} / py${{ matrix.python }}) ==="
          if [ -f ui_summary.json ]; then
            echo "✅ UI Reporter executado com sucesso"
            echo "📊 Checks realizados:"
            python -c "import json; data=json.load(open('ui_summary.json')); [print(f'  {k}: {\"✅\" if v else \"❌\"}') for k,v in data['checks'].items()]"
          else
            echo "❌ UI Reporter falhou"
            exit 1
          fi
